baseurl = "/"
languageCode = "en-us"
title = "Cville R users"
theme = "blackburn"
author = "CvilleRs"
copyright = "&copy; 2018. All rights reserved."
canonifyurls = true
paginate = 10
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files/", "_cache$"]

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "A resource for past meetup materials"
  brand = "Cville UseRs"
  googleAnalytics = "Your Google Analytics tracking ID"
  disqus = ""
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "About CvilleRs"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 2
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Archives"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 3
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Projects"
    pre = "<i class='fa fa-wrench fa-fw'></i>"
    weight = 4
    url = "/projects/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  #twitter = "*"
  #facebook = "*"
  #instagram = "*"
  github = "UVa-R-Users-Group"
  #stackoverflow = "*"
  #linkedin = "*"
